### ISSUE TITLE
Automatic build

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/ocamhaxe#3]
It would be nice if for each commit on `ocamhaxe` we run that on a windows build machine to create a distribution.

What's required is:
a) clone ocamhaxe
b) run haxe/Build.exe
c) zip the resulting ocamhaxe directory
d) upload it somewhere it can be accessed publicly

Could you help @andyli ?

**Comment by andyli** [comment]
No problem. Will look into it :)

**Comment by andyli** [comment]
Currently my understanding is: To build the ocamhaxe zip, one has to have an existing cygwin installation, with all the required cygwin packages installed. `haxe/Build.exe` will then copy the cygwin things and fdopen things and put them into a folder, finally zip it.

I wonder shouldn't we reuse the cygwin setup.exe installer for setting up the cygwin environment (instead of manually copying files). I'm thinking, ideally, we can merge Config.exe and Build.exe, to have a single program (e.g. OcamHaxe.exe), that accept a single argument which is the path to a cygwin installation. If the path exist, it will use cygwin's setup.exe and fdopen's installer script to set things up. If the path doesn't exist, again, it will use cygwin's setup.exe to create a cygwin environment, then run fdopen's installer.

In this case, we don't have to prepackage the cygwin/opam stuff and users will be able to get the latest version of things when they run the OcamHaxe.exe. We just need to publish the OcamHaxe.exe.

**Comment by ncannasse** [comment]
I'm not sure the whole automation is necessary or good. When it comes to do
everything from scratch, it takes a lot of time to rebuild ocaml and setup
everything (like minutes), and it might even be worse depending on your net
connection. Also, there is a high risk our entire setup is broken by one of
the dependencies having a minor change. So I think we should really
distribute our own "everything's ready" distribution, it's better for both
us and users.

**Comment by andyli** [comment]
I agree on the case when building from scratch (no existing cygwin). But when there is an existing cygwin, copying files to there instead of using cygwin's setup.exe results in the exact potential of breakage. e.g. When the user has a more updated lib but we copied an older version there.

**Comment by andyli** [comment]
BTW, a small detail: fdopen's installer by default do not compile OCaml, it just downloads a pre-compiled one. It's the opam packages (e.g. sedlex) have to be compiled.

**Comment by ncannasse** [comment]
@andyli we don't copy any file to cygwin. If there's an existing cygwin, we only check that the required tools are here and tell the user if some is missing. The mingw distrib we are building is only used when there is no existing cygwin installation found

**Comment by andyli** [comment]
I see. I'm not sure if ocamhaxe would be that useful for existing cygwin installation, but I will proceed to automate the dist creation.

**Comment by Simn** [comment]
I'll close this because it isn't going to happen, and it's not like ocamhaxe receives many commits that would require this. As long as we remember to rebuild the exes at some point this should be pragmatic enough.
